### ISSUE TITLE
Method for customizing abbreviations

### ISSUE THREAD

**Issue by SterlingHooten** [astoff/unicode-math-input.el#1]
Is there a way to add or customize the shortcuts used? Some common things like \QED would be easier to type as \qed. But evaluating (add-to-list 'unicode-math-input-symbols '("iff" . #x027FA)) doesn't seem to work interactively. It will show up if I call unicode-math-input, but not in the input mode.

**Comment by astoff** [comment]
You can take a look at this: https://emacs.stackexchange.com/questions/3104/how-can-i-add-characters-to-an-input-method/3404#3404

I should probably add a word on this to the Readme.
